#!/bin/sh
# Every commit carries the committer's DCO sign-off (docs/dev-rules/git-and-github.md, section 1.2).
set -eu
ident=$(git var GIT_COMMITTER_IDENT | sed 's/ [0-9][0-9]* [-+][0-9][0-9][0-9][0-9]$//')
exec git interpret-trailers --in-place --if-exists addIfDifferent --trailer "Signed-off-by: $ident" "$1"
