version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore(ci)
