import fs from "node:fs";
import path from "node:path";
import { fingerprintKeys, p95, p99, readJson } from "./lib.mjs";

const REPORT_GENERATOR = "scripts/stage/test.mjs";

function checkP95(errors, bench, values, label, metric, limit) {
  if (!Array.isArray(values) || values.length < 3 || values.some((value) => !Number.isFinite(value) || value < 0)) {
    errors.push(`bench.json: ${label} samples invalid`);
    return;
  }
  if (limit !== undefined && p95(values) > limit) errors.push(`bench.json: ${label} exceeds ${metric} target`);
  if (bench.metrics?.[metric] !== p95(values)) errors.push(`bench.json: ${metric} does not match its raw samples`);
}

/**
 * Evaluate one run directory against the stage configuration. Missing files, results from a different
 * source/lock/test/build state, failed cases and absent measurements are all errors. The report never
 * computes product acceptance.
 */
export function evaluateStageEvidence(dir, fingerprints, config) {
  const errors = [];
  const current = (name, item) => {
    if (!item) {
      errors.push(`${name}: missing or invalid JSON`);
      return false;
    }
    for (const key of fingerprintKeys) {
      if (item[key] !== fingerprints[key]) {
        errors.push(`${name}: missing or stale ${key}`);
        return false;
      }
    }
    return true;
  };

  const cases = readJson(dir, "cases.json");
  if (current("cases.json", cases)) {
    const results = Array.isArray(cases.cases) ? cases.cases : [];
    for (const def of config.cases) {
      const matches = results.filter((entry) => entry.caseId === def.id);
      if (matches.length !== 1 || matches[0].kind !== def.kind) {
        errors.push(`cases.json: missing, duplicate or reclassified case ${def.id}`);
        continue;
      }
      const entry = matches[0];
      if (entry.status !== "passed") errors.push(`${def.id}: required automated case is ${entry.status}`);
      const tests = Array.isArray(entry.tests) ? entry.tests : [];
      if (tests.length < (def.tests ?? []).length || tests.some((test) => test.status !== "passed" || !test.name || !test.file)) {
        errors.push(`${def.id}: executed tests missing or not passed`);
      }
      for (const pattern of def.tests ?? []) {
        if (!tests.some((test) => new RegExp(pattern).test(test.name))) errors.push(`${def.id}: missing test ${pattern}`);
      }
    }
    if (cases.generator !== REPORT_GENERATOR) errors.push(`cases.json: not generated by ${REPORT_GENERATOR}`);
    if (cases.productAcceptance === "passed") errors.push("cases.json: product acceptance must not be computed by the report");
  }

  const testRun = readJson(dir, "test-run.json");
  current("test-run.json", testRun);
  if (testRun && testRun.status !== "passed") errors.push("test-run.json: result is not passed");

  const bench = readJson(dir, "bench.json");
  current("bench.json", bench);
  if (bench && bench.status !== "passed") errors.push("bench.json: result is not passed");
  if (bench) {
    const { targets, scale: requiredScale, scaleWindowSamples } = config.bench;
    for (const [metric, limit] of Object.entries(targets)) {
      if (bench.targets?.[metric] !== limit) errors.push(`bench.json: target ${metric} missing or changed`);
      const value = bench.metrics?.[metric];
      if (!Number.isFinite(value) || value < 0 || value > limit) errors.push(`bench.json: metric ${metric} missing or over target`);
    }
    if ((bench.scale?.metadataCount ?? 0) < requiredScale.metadataCount) errors.push("bench.json: metadataCount below 10000");
    if ((bench.scale?.searchBlocks ?? 0) < requiredScale.searchBlocks) errors.push("bench.json: searchBlocks below 50000");
    const rawCounts = [["searchMs", 20, "search"], ["indexedFirstScreenMs", 5, "indexed first screen"], ["reparseMs", 3, "reparse"], ["operationContentMs", 5, "operation content-available"], ["operationSaveMs", 5, "operation save-receipt"], ["windowContentMs", 3, "window content"], ["windowSaveMs", 3, "window save"], ["windowImportMs", 3, "window import"]];
    for (const [key, minimum, label] of rawCounts) {
      if (!Array.isArray(bench.raw?.[key]) || bench.raw[key].length < minimum) errors.push(`bench.json: ${label} raw samples missing`);
    }
    if (bench.samples?.coldStartMs?.kind !== "process") errors.push("bench.json: cold start is not a process sample");
    if (bench.samples?.interactionMs?.kind !== "electron") errors.push("bench.json: interaction is not an Electron sample");
    if (bench.samples?.interactionMs?.waitedForContent !== true) errors.push("bench.json: interaction stopped before the renderer showed content");
    if (bench.samples?.windowContentMs?.kind !== "electron-content-visible") errors.push("bench.json: window content timing is not an Electron sample");
    if (bench.samples?.windowSaveMs?.kind !== "electron-save-receipt") errors.push("bench.json: window save timing is not an Electron receipt");
    if (bench.samples?.windowImportMs?.kind !== "electron-import-to-readable") errors.push("bench.json: window import timing is not measured to a readable page");
    for (const [rawKey, metric] of [["windowContentMs", "contentAvailableP95Ms"], ["windowSaveMs", "saveReceiptP95Ms"], ["windowImportMs", "importToReadableP95Ms"]]) {
      checkP95(errors, bench, bench.raw?.[rawKey], rawKey, metric, targets[metric]);
    }
    // The service dataset and short window samples cannot stand in for the same-scale window run.
    const scale = bench.scaleWindow;
    if (scale?.kind !== "electron-scale-profile" || scale.ok !== true) errors.push("bench.json: scale window run missing or incomplete");
    if ((scale?.scale?.metadataCount ?? 0) < requiredScale.metadataCount || (scale?.scale?.searchBlocks ?? 0) < requiredScale.searchBlocks) errors.push("bench.json: scale window Profile below the benchmark library");
    if ((scale?.sizes?.txtBytes ?? 0) < 10 * 1024 * 1024 || (scale?.sizes?.epubBytes ?? 0) < 30 * 1024 * 1024 || (scale?.sizes?.backgroundBytes ?? 0) < 10 * 1024 * 1024) errors.push("bench.json: scale window books below 10 MiB TXT / 30 MiB EPUB");
    for (const [metric, [rawKey, minimum]] of Object.entries(scaleWindowSamples)) {
      const values = scale?.raw?.[rawKey];
      if (!Array.isArray(values) || values.length < minimum || values.some((value) => !Number.isFinite(value) || value < 0)) {
        errors.push(`bench.json: scale ${rawKey} samples invalid`);
        continue;
      }
      if (bench.metrics?.[metric] !== p95(values)) errors.push(`bench.json: ${metric} does not match scale window samples`);
    }
    if (!Array.isArray(scale?.raw?.samplesWhileParsing) || scale.raw.samplesWhileParsing.some((count) => !(count >= 2))) errors.push("bench.json: scale window did not sample the UI while parsing");
    if (bench.samples?.contentAvailableMs?.kind !== "operation-to-content") errors.push("bench.json: content availability is not an operation-level sample");
    if (bench.samples?.saveReceiptMs?.kind !== "operation-to-commit-receipt") errors.push("bench.json: save is not measured to a commit receipt");
    // The rework's 5000-file scan: every run reached the full file count, and both gated figures follow from their raw samples.
    const rework = bench.rework;
    const wanted = config.bench.scan;
    if (wanted) {
      const scan = rework?.scan;
      const each = (values) => Array.isArray(values) && values.length >= wanted.runs;
      if (rework?.ok !== true || !scan || !each(scan.files) || scan.files.some((count) => count < wanted.files) || !each(scan.added) || scan.added.some((count, index) => count < scan.files[index])) {
        errors.push("bench.json: the 5000-file scan did not run to the full file count in every run");
      }
      const lag = scan?.loopLag?.raw;
      if (!Array.isArray(lag) || lag.length < wanted.minLagSamples || lag.some((value) => !Number.isFinite(value) || value < 0)) errors.push("bench.json: scan event-loop delay samples invalid");
      else if (bench.metrics?.scanEventLoopP99Ms !== p99(lag)) errors.push("bench.json: scanEventLoopP99Ms does not match its raw samples");
      const answers = scan?.interaction?.raw;
      if (!Array.isArray(answers) || answers.length < wanted.minAnswerSamples || answers.some((value) => !Number.isFinite(value) || value < 0)) errors.push("bench.json: scan interaction samples invalid");
      else if (bench.metrics?.scanInteractionP95Ms !== p95(answers)) errors.push("bench.json: scanInteractionP95Ms does not match its raw samples");
      if (rework?.pane?.kind !== "electron-pane-1000" || !Array.isArray(rework.pane.loaded) || rework.pane.loaded.some((count) => count < 1000)) errors.push("bench.json: the right pane was not measured with 1000 messages in the window");
    }
    // Measurement-only figures: the raw samples and their p95 must exist; they are not pass/fail limits.
    for (const item of config.bench.measurements ?? []) {
      const entry = bench.measurements?.[item.id];
      if (!entry || !Array.isArray(entry.raw) || entry.raw.length < (item.minSamples ?? 3) || entry.raw.some((value) => !Number.isFinite(value) || value < 0)) {
        errors.push(`bench.json: measurement ${item.id} raw samples missing`);
        continue;
      }
      if (entry.p95 !== p95(entry.raw)) errors.push(`bench.json: measurement ${item.id} p95 does not match its raw samples`);
    }
    if (bench.productAcceptance === "passed") errors.push("bench.json: product acceptance must not be computed");
  }

  const pack = readJson(dir, "package.json");
  current("package.json", pack);
  if (pack && pack.status !== "passed") errors.push("package.json: result is not passed");
  if (pack) {
    for (const phase of config.package.smoke) {
      if (!(pack.smoke ?? []).includes(phase)) errors.push(`package.json: ${phase} smoke missing`);
    }
    if (pack.formats?.pages !== true || pack.formats?.modes !== true || pack.formats?.failureVisible !== true) errors.push("package.json: formats smoke did not cover pages, modes and the failed import");
    if (!pack.output) errors.push("package.json: output missing");
    if (typeof pack.electron !== "string" || !/^\d+\.\d+\.\d+/.test(pack.electron)) errors.push("package.json: Electron version missing");
    // The closure run must prove the reading→record→source loop and restart recovery really ran.
    const closure = pack.closure;
    if (!closure) errors.push("package.json: closure smoke result missing");
    for (const key of ["readLastChapter", "recordedNote", "sourceCardOk", "restoredProgress"]) {
      if (closure?.[key] !== true) errors.push(`package.json: closure ${key} is not true`);
    }
    const timings = closure?.timings ?? {};
    for (const key of ["importMs", "tailMs", "noteMs", "selectionMs"]) {
      if (!Number.isFinite(timings[key]) || timings[key] < 0) errors.push(`package.json: closure timing ${key} missing`);
    }
    // LOOP-06: the PDF page is painted once at its opening width and not again after the width has held still, with the selection kept.
    const loop = pack.loop06;
    if (loop?.settled?.stable !== true || loop?.tagged !== true || loop?.repainted !== false || loop?.atEnd?.nodeConnected !== true) errors.push("package.json: the PDF selection was not kept through the settled page (LOOP-06)");
    if (pack.agent?.runningShown !== true || pack.agent?.stoppedShown !== true || pack.agent?.conversationShown !== true) errors.push("package.json: agent smoke did not show the stop control, the send control after it, and the conversation after a restart");
    if (pack.rework?.ok !== true || !(pack.rework?.observations >= (config.scenarios ?? []).length)) errors.push("package.json: the rework walk did not run to its end");
    for (const size of ["wide", "narrow"]) {
      if (!(pack.viewports?.[size]?.innerWidth > 0)) errors.push(`package.json: ${size} viewport missing`);
    }
    for (const asset of config.package.assets ?? []) {
      if (pack.assets?.[asset] !== true) errors.push(`package.json: packaged asset ${asset} missing or not verified`);
    }
    if (pack.productAcceptance === "passed") errors.push("package.json: product acceptance must not be computed");
  }

  // Packaged-window scenarios: each required observation must exist once and be passed.
  if (config.scenarios?.length) {
    const scenarios = readJson(dir, "scenarios.json");
    if (current("scenarios.json", scenarios)) {
      const observed = new Map((scenarios.observations ?? []).map((row) => [row.name, row]));
      for (const name of config.scenarios) {
        const row = observed.get(name);
        if (!row) errors.push(`scenarios.json: missing observation ${name}`);
        else if (row.status !== "passed") errors.push(`scenarios.json: observation ${name} is ${row.status}`);
      }
      if (scenarios.productAcceptance === "passed") errors.push("scenarios.json: product acceptance must not be computed");
    }
  }

  // Declared limits (blocked, not-run) are allowed only when each carries an owner and a retest entry.
  const limits = readJson(dir, "limits.json");
  if (limits) {
    for (const entry of limits.entries ?? []) {
      if (!["blocked", "not-run"].includes(entry.status)) errors.push(`limits.json: ${entry.id} has unknown status ${entry.status}`);
      if (!entry.owner || !entry.retest) errors.push(`limits.json: ${entry.id} needs an owner and a retest entry`);
    }
  }

  return {
    errors: [...new Set(errors)],
    automationStatus: errors.length ? "failed-or-incomplete" : "self-check-passed",
    engineeringReviewable: errors.length === 0,
    productAcceptance: "not-run",
  };
}

export function writeReport(dir, fingerprints, config) {
  const report = evaluateStageEvidence(dir, fingerprints, config);
  fs.writeFileSync(path.join(dir, "report.json"), `${JSON.stringify({ ...report, ...fingerprints, at: new Date().toISOString() }, null, 2)}\n`);
  return report;
}
