export { MangaProductApp, type ProductAppOptions } from "./product-app.ts";
export { resolveLaunchLayout, persistPointer, defaultPointerPath, type LaunchRequest } from "./locations.ts";
export { TestVault, UnavailableVault, ElectronSafeStorageVault, type CredentialVault } from "./credentials.ts";
export { GrantRegistry } from "./grants.ts";
export { exportLibraryPackage, importLibraryPackage, recoverOrRollback, previewLibraryPackage, importLibraryPackageResolved } from "./domain/library-package.ts";
export { parseDocument, parseDocumentBytes, parseEpubBytes, parseMobiBytes, parsePdfBytes, parseTextBytes, buildEpubFixture, buildMobiFixture, buildPdfFixture, buildPdfObjectStreamFixture, buildZip, readZip, palmdocDecompress, htmlToText, htmlImageSources, htmlSvgImageHrefs, sniffFormat } from "./domain/formats.ts";
export { applyNoteOp, coerceNoteDocument, notePlainText, uniqueBlockIds, isKnownBlockType } from "./domain/note-document.ts";
export { resolveTextLocator, findQuoteMatches } from "./domain/anchors.ts";
export { deriveShell, reduceHover, initialHover, defaultShell } from "./domain/shell-layout.ts";
export { builtinReaderEngine, type ReaderEngine, type ReaderEngineDocument, type ReaderEnginePart, type ReaderEngineTextRun } from "./domain/reader-engine.ts";
export { readShell } from "./reading-service.ts";
