import fs from "node:fs";
import path from "node:path";
import required from "./m1a-required-cases.json" with { type: "json" };

export const requiredBenchTargets = {
  searchP95Ms: 500,
  saveMs: 1000,
  coldStartMs: 5000,
  contextP95Ms: 150,
  interactionP95Ms: 8000,
};

export const requiredScale = {
  metadataCount: 10_000,
  searchBlocks: 50_000,
};

export const requiredBenchRaw = {
  searchMs: 100,
  saveMs: 10,
  contextMs: 10,
  coldStartMs: 3,
  interactionMs: 3,
};

function readJson(dir, name) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, name), "utf8"));
  } catch {
    return null;
  }
}

export function evaluateM1aEvidence(dir, fingerprints) {
  const errors = [];
  const sourceFingerprint = fingerprints.sourceFingerprint;
  const m1aSourceFingerprint = fingerprints.m1aSourceFingerprint;
  const current = (name, item) => {
    if (!item) {
      errors.push(`${name}: missing or invalid JSON`);
      return false;
    }
    if (item.sourceFingerprint !== sourceFingerprint) {
      errors.push(`${name}: missing or stale sourceFingerprint`);
      return false;
    }
    if (item.m1aSourceFingerprint !== m1aSourceFingerprint) {
      errors.push(`${name}: missing or stale m1aSourceFingerprint`);
      return false;
    }
    return true;
  };

  for (const [file, expected] of Object.entries(required)) {
    const item = readJson(dir, file);
    const valid = current(file, item);
    const cases = Array.isArray(item?.cases) ? item.cases : [];
    if (!valid) continue;
    for (const def of expected) {
      const matches = cases.filter((entry) => entry.caseId === def.id);
      if (matches.length !== 1 || matches[0].kind !== def.kind) {
        errors.push(`${file}: missing, duplicate or reclassified case ${def.id}`);
        continue;
      }
      const entry = matches[0];
      if (!["passed", "failed", "not-run", "blocked"].includes(entry.status)) errors.push(`${def.id}: invalid status`);
      else if (entry.status === "failed") errors.push(`${def.id}: failed`);
      else if (entry.status !== "passed") errors.push(`${def.id}: required automated case not completed`);
      // A case is only evidence when it names the executed tests behind it; a bare status is a claim, not a result.
      const tests = Array.isArray(entry.tests) ? entry.tests : [];
      const expected = Array.isArray(def.tests) ? def.tests.length : 0;
      if (tests.length < Math.max(1, expected) || tests.some((item) => item.status !== "passed" || !item.name || !item.file)
        || (def.tests ?? []).some((pattern) => !tests.some((item) => new RegExp(pattern).test(item.name)))) {
        errors.push(`${def.id}: executed tests missing, incomplete or not passed`);
      }
    }
    if (item.generator !== "scripts/verify-m1a.mjs") errors.push(`${file}: not generated by scripts/verify-m1a.mjs`);
  }

  const testRun = readJson(dir, "test-run.json");
  current("test-run.json", testRun);
  if (testRun && testRun.status !== "passed") errors.push("test-run.json: result is not passed");

  const bench = readJson(dir, "bench.json");
  current("bench.json", bench);
  if (bench && bench.status !== "passed") errors.push("bench.json: result is not passed");
  if (bench) {
    for (const [metric, limit] of Object.entries(requiredBenchTargets)) {
      if (bench.targets?.[metric] !== limit) errors.push(`bench.json: target ${metric} missing or changed`);
      const value = bench.metrics?.[metric];
      if (!Number.isFinite(value) || value < 0 || value > limit) errors.push(`bench.json: metric ${metric} missing or over target`);
    }
    if ((bench.scale?.metadataCount ?? 0) < requiredScale.metadataCount) errors.push("bench.json: metadataCount below 10000");
    if ((bench.scale?.searchBlocks ?? 0) < requiredScale.searchBlocks) errors.push("bench.json: searchBlocks below 50000");
    const raw = bench.raw ?? {};
    if (!Array.isArray(raw.searchMs) || raw.searchMs.length < requiredBenchRaw.searchMs) errors.push("bench.json: search raw samples missing");
    if (!Array.isArray(raw.saveMs) || raw.saveMs.length < requiredBenchRaw.saveMs) errors.push("bench.json: save raw samples missing");
    if (!Array.isArray(raw.contextMs) || raw.contextMs.length < requiredBenchRaw.contextMs) errors.push("bench.json: context raw samples missing");
    if (!Array.isArray(raw.coldStartMs) || raw.coldStartMs.length < requiredBenchRaw.coldStartMs) errors.push("bench.json: process cold start samples missing");
    if (!Array.isArray(raw.interactionMs) || raw.interactionMs.length < requiredBenchRaw.interactionMs) errors.push("bench.json: visible interaction samples missing");
    if (bench.samples?.coldStartMs?.kind !== "process") errors.push("bench.json: cold start is not a real process sample");
    if (bench.samples?.interactionMs?.kind !== "electron") errors.push("bench.json: interaction is not an Electron sample");
  }

  const pack = readJson(dir, "package.json");
  current("package.json", pack);
  if (pack && pack.status !== "passed") errors.push("package.json: result is not passed");
  if (pack) {
    const smoke = pack.smoke ?? pack.smokeResults;
    const names = Array.isArray(smoke)
      ? smoke.map((item) => typeof item === "string" ? item : item.phase)
      : [];
    for (const phase of ["initial", "restart", "agent", "agent-restart"]) {
      if (!names.includes(phase)) errors.push(`package.json: ${phase} smoke missing`);
    }
  }

  // Independent A audits may reproduce requirements outside the automated regression subset.
  // Their failures must not disappear behind a green unit-test or packaging report.
  if (fs.existsSync(path.join(dir, "audit.json"))) {
    const audit = readJson(dir, "audit.json");
    current("audit.json", audit);
    if (audit?.status !== "no-open-finding-reproduced") errors.push("audit.json: unresolved technical findings");
    for (const item of audit?.observations ?? []) {
      if (item.status !== "passed") errors.push(`audit.json: ${item.finding} ${item.scenario}`);
    }
  }

  return {
    errors: [...new Set(errors)],
    automationStatus: errors.length ? "failed-or-incomplete" : "tested-subset-passed",
    engineeringReviewable: errors.length === 0,
  };
}
