import fs from "node:fs";
import path from "node:path";
import required from "./m1b-required-cases.json" with { type: "json" };

export const requiredBenchTargets = {
  searchP95Ms: 500,
  contextP95Ms: 150,
  indexedFirstScreenMs: 2000,
  saveMs: 1000,
  progressSaveMs: 1000,
  coldStartMs: 5000,
  interactionP95Ms: 8000,
  // Operation-level figures, so the measurable path is content-available and save-receipt.
  contentAvailableP95Ms: 2000,
  saveReceiptP95Ms: 1000,
  importToReadableP95Ms: 5000,
  // Requirement 6.2 measured in the real window on a benchmark-scale Profile with the large books.
  scaleColdStartToLibraryMs: 5000,
  scaleUiFeedbackP95Ms: 100,
  scaleLargeTxtTailP95Ms: 2000,
  scaleLargeEpubTailP95Ms: 2000,
  scaleSaveReceiptP95Ms: 1000,
  scaleDuringParseUiP95Ms: 100,
  scaleDuringParseSaveP95Ms: 1000,
};

/** Raw scale-window samples behind each 6.2 metric, with the minimum sample count a p95 may rest on. */
export const scaleWindowSamples = {
  scaleColdStartToLibraryMs: ["coldStartToLibraryMs", 3],
  scaleUiFeedbackP95Ms: ["uiFeedbackMs", 10],
  scaleLargeTxtTailP95Ms: ["largeTxtTailMs", 3],
  scaleLargeEpubTailP95Ms: ["largeEpubTailMs", 3],
  scaleSaveReceiptP95Ms: ["saveReceiptMs", 5],
  scaleDuringParseUiP95Ms: ["duringParseUiMs", 3],
  scaleDuringParseSaveP95Ms: ["duringParseSaveMs", 1],
};

export const requiredScale = { metadataCount: 10_000, searchBlocks: 50_000 };

/** Packaged and service counterexamples that a strict M1b report must include. Missing the file is not a pass. */
export const requiredPdfCounterexamples = [
  "replace anchor control",
  "duplicate anchor retains payload/ref/history agreement",
  "duplicate resource and anchor keeps skipped ref revision owner",
  "duplicate resource with replaced anchor keeps skipped source identity",
  "packaged single excerpt and source highlight",
  "packaged multiline excerpt and source highlight",
  "text-layer hit area follows Canvas glyph scale",
  "new PDF multiline selection has a usable locator",
  "new PDF repeated selection has a usable locator",
  "scan page paints nonblank Canvas and has no selectable text",
  "late original bytes cannot replace the current book",
  "packaged PDF runs without HTTP or HTTPS",
  "persisted PDF excerpts equal the selected quotes",
  "mouse drag selects a line with Chinese, emoji, NFC and spaces",
  "mouse drag across lines keeps the end-of-line in the quote",
  "zoom and the next page keep the text-layer hit area",
  "late original failure cannot clear the current book or its session",
  "embedded font and substitute font stay distinct",
  "development server serves pdf.js assets from the local package",
  "old revision ambiguity stays needs review and a missing original keeps the note",
];

const fingerprintKeys = ["sourceFingerprint", "m1bSourceFingerprint", "lockFingerprint", "testScriptFingerprint", "buildScriptFingerprint"];

function readJson(dir, name) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, name), "utf8"));
  } catch {
    return null;
  }
}

export function evaluateM1bEvidence(dir, fingerprints, options = {}) {
  const errors = [];
  const current = (name, item) => {
    if (!item) {
      errors.push(`${name}: missing or invalid JSON`);
      return false;
    }
    for (const key of fingerprintKeys) {
      if (item[key] !== fingerprints[key]) {
        errors.push(`${name}: missing or stale ${key}`);
        return false;
      }
    }
    return true;
  };

  for (const [file, expected] of Object.entries(required)) {
    const item = readJson(dir, file);
    const valid = current(file, item);
    const cases = Array.isArray(item?.cases) ? item.cases : [];
    if (!valid) continue;
    for (const def of expected) {
      const matches = cases.filter((entry) => entry.caseId === def.id);
      if (matches.length !== 1 || matches[0].kind !== def.kind) {
        errors.push(`${file}: missing, duplicate or reclassified case ${def.id}`);
        continue;
      }
      const entry = matches[0];
      if (entry.status !== "passed") errors.push(`${def.id}: required automated case is ${entry.status}`);
      const tests = Array.isArray(entry.tests) ? entry.tests : [];
      if (tests.length < (def.tests ?? []).length || tests.some((test) => test.status !== "passed" || !test.name || !test.file)) {
        errors.push(`${def.id}: executed tests missing or not passed`);
      }
      for (const pattern of def.tests ?? []) {
        if (!tests.some((test) => new RegExp(pattern).test(test.name))) errors.push(`${def.id}: missing test ${pattern}`);
      }
    }
    if (item.generator !== "scripts/verify-m1b.mjs") errors.push(`${file}: not generated by scripts/verify-m1b.mjs`);
    if (item.productAcceptance === "passed") errors.push(`${file}: product acceptance must not be computed by the report`);
  }

  const testRun = readJson(dir, "test-run.json");
  current("test-run.json", testRun);
  if (testRun && testRun.status !== "passed") errors.push("test-run.json: result is not passed");

  const bench = readJson(dir, "bench.json");
  current("bench.json", bench);
  if (bench && bench.status !== "passed") errors.push("bench.json: result is not passed");
  if (bench) {
    for (const [metric, limit] of Object.entries(requiredBenchTargets)) {
      if (bench.targets?.[metric] !== limit) errors.push(`bench.json: target ${metric} missing or changed`);
      const value = bench.metrics?.[metric];
      if (!Number.isFinite(value) || value < 0 || value > limit) errors.push(`bench.json: metric ${metric} missing or over target`);
    }
    if ((bench.scale?.metadataCount ?? 0) < requiredScale.metadataCount) errors.push("bench.json: metadataCount below 10000");
    if ((bench.scale?.searchBlocks ?? 0) < requiredScale.searchBlocks) errors.push("bench.json: searchBlocks below 50000");
    if (!Array.isArray(bench.raw?.searchMs) || bench.raw.searchMs.length < 20) errors.push("bench.json: search raw samples missing");
    if (!Array.isArray(bench.raw?.indexedFirstScreenMs) || bench.raw.indexedFirstScreenMs.length < 5) errors.push("bench.json: indexed first screen samples missing");
    if (!Array.isArray(bench.raw?.reparseMs) || bench.raw.reparseMs.length < 3) errors.push("bench.json: reparse samples missing");
    if (!Array.isArray(bench.raw?.operationContentMs) || bench.raw.operationContentMs.length < 5) errors.push("bench.json: operation content-available samples missing");
    if (!Array.isArray(bench.raw?.operationSaveMs) || bench.raw.operationSaveMs.length < 5) errors.push("bench.json: operation save-receipt samples missing");
    if (bench.samples?.coldStartMs?.kind !== "process") errors.push("bench.json: cold start is not a process sample");
    if (bench.samples?.interactionMs?.kind !== "electron") errors.push("bench.json: interaction is not an Electron sample");
    if (bench.samples?.interactionMs?.waitedForContent !== true) errors.push("bench.json: interaction stopped before the renderer showed content");
    if (bench.samples?.windowContentMs?.kind !== "electron-content-visible") errors.push("bench.json: window content timing is not an Electron sample");
    if (bench.samples?.windowSaveMs?.kind !== "electron-save-receipt") errors.push("bench.json: window save timing is not an Electron receipt");
    if (bench.samples?.windowImportMs?.kind !== "electron-import-to-readable") errors.push("bench.json: window import timing is not measured to a readable page");
    if (!Array.isArray(bench.raw?.windowContentMs) || bench.raw.windowContentMs.length < 3) errors.push("bench.json: window content samples missing");
    if (!Array.isArray(bench.raw?.windowSaveMs) || bench.raw.windowSaveMs.length < 3) errors.push("bench.json: window save samples missing");
    if (!Array.isArray(bench.raw?.windowImportMs) || bench.raw.windowImportMs.length < 3) errors.push("bench.json: window import samples missing");
    for (const [rawKey, metric] of [
      ["windowContentMs", "contentAvailableP95Ms"],
      ["windowSaveMs", "saveReceiptP95Ms"],
      ["windowImportMs", "importToReadableP95Ms"],
    ]) {
      const values = bench.raw?.[rawKey];
      if (!Array.isArray(values) || values.length < 3 || values.some((value) => !Number.isFinite(value) || value < 0)) {
        errors.push(`bench.json: ${rawKey} samples invalid`);
        continue;
      }
      const sorted = [...values].sort((a, b) => a - b);
      const p95 = sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * 0.95))];
      if (p95 > requiredBenchTargets[metric]) errors.push(`bench.json: ${rawKey} exceeds ${metric} target`);
      if (bench.metrics?.[metric] !== p95) errors.push(`bench.json: ${metric} does not match Electron samples`);
    }
    // The service dataset and short window samples cannot stand in for the same-scale window run.
    const scale = bench.scaleWindow;
    if (scale?.kind !== "electron-scale-profile" || scale.ok !== true) errors.push("bench.json: scale window run missing or incomplete");
    if ((scale?.scale?.metadataCount ?? 0) < requiredScale.metadataCount || (scale?.scale?.searchBlocks ?? 0) < requiredScale.searchBlocks) errors.push("bench.json: scale window Profile below the benchmark library");
    if ((scale?.sizes?.txtBytes ?? 0) < 10 * 1024 * 1024 || (scale?.sizes?.epubBytes ?? 0) < 30 * 1024 * 1024 || (scale?.sizes?.backgroundBytes ?? 0) < 10 * 1024 * 1024) errors.push("bench.json: scale window books below 10 MiB TXT / 30 MiB EPUB");
    for (const [metric, [rawKey, minimum]] of Object.entries(scaleWindowSamples)) {
      const values = scale?.raw?.[rawKey];
      if (!Array.isArray(values) || values.length < minimum || values.some((value) => !Number.isFinite(value) || value < 0)) {
        errors.push(`bench.json: scale ${rawKey} samples invalid`);
        continue;
      }
      const sorted = [...values].sort((a, b) => a - b);
      const p95 = sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * 0.95))];
      if (bench.metrics?.[metric] !== p95) errors.push(`bench.json: ${metric} does not match scale window samples`);
    }
    if (!Array.isArray(scale?.raw?.samplesWhileParsing) || scale.raw.samplesWhileParsing.some((count) => !(count >= 2))) errors.push("bench.json: scale window did not sample the UI while parsing");
    if (bench.samples?.contentAvailableMs?.kind !== "operation-to-content") errors.push("bench.json: content availability is not an operation-level sample");
    if (bench.samples?.saveReceiptMs?.kind !== "operation-to-commit-receipt") errors.push("bench.json: save is not measured to a commit receipt");
    if (bench.productAcceptance === "passed") errors.push("bench.json: product acceptance must not be computed");
  }

  const pack = readJson(dir, "package.json");
  current("package.json", pack);
  if (pack && pack.status !== "passed") errors.push("package.json: result is not passed");
  if (pack) {
    for (const phase of ["initial", "restart", "agent", "agent-restart", "reading", "closure", "closure-restart", "formats"]) {
      if (!(pack.smoke ?? []).includes(phase)) errors.push(`package.json: ${phase} smoke missing`);
    }
    if (pack.formats?.pages !== true || pack.formats?.modes !== true || pack.formats?.failureVisible !== true) errors.push("package.json: formats smoke did not cover pages, modes and the failed import");
    if (!pack.output) errors.push("package.json: output missing");
    // The closure run must prove the reading→record→source loop and restart recovery really ran.
    const closure = pack.closure;
    if (!closure) errors.push("package.json: closure smoke result missing");
    for (const key of ["readLastChapter", "recordedNote", "sourceCardOk", "restoredProgress"]) {
      if (closure?.[key] !== true) errors.push(`package.json: closure ${key} is not true`);
    }
    const timings = closure?.timings ?? {};
    for (const key of ["importMs", "tailMs", "noteMs", "selectionMs"]) {
      if (!Number.isFinite(timings[key]) || timings[key] < 0) errors.push(`package.json: closure timing ${key} missing`);
    }
    if (pack.productAcceptance === "passed") errors.push("package.json: product acceptance must not be computed");
  }

  if (options.requirePdfCounterexamples) {
    const audit = readJson(dir, "a-adversarial-review.json");
    if (current("a-adversarial-review.json", audit) && Array.isArray(audit.observations)) {
      const passed = new Set(audit.observations.filter((row) => row.status === "passed").map((row) => row.name));
      for (const name of requiredPdfCounterexamples) {
        if (!passed.has(name)) errors.push(`a-adversarial-review.json: missing passed counterexample ${name}`);
      }
    }
  }

  // A review in this run cannot be hidden by the narrower B self-check subset.
  for (const name of ["a-adversarial-review.json", "a-additional-ui-review.json", "a-b5-deep-review.json", "a-b5-h-checks.json", "a-b6-deep-review.json", "a-b6-ui-review.json", "a-b7-rework-review.json", "a-b7-deep-review.json", "a-b7-ui-review.json", "a-b8-independent-review.json", "reader-engine-evidence.json"]) {
    if (!fs.existsSync(path.join(dir, name))) continue;
    const audit = readJson(dir, name);
    if (!current(name, audit)) continue;
    if (audit.status !== "passed" || !Array.isArray(audit.observations) || !audit.observations.length || audit.observations.some((row) => row.status !== "passed")) {
      errors.push(`${name}: independent review failed or incomplete`);
    }
  }

  return {
    errors: [...new Set(errors)],
    automationStatus: errors.length ? "failed-or-incomplete" : "self-check-passed",
    engineeringReviewable: errors.length === 0,
    productAcceptance: "not-run",
  };
}
